spring:
  application:
    name: topics-tracker
  profiles.active: hk-zone-1
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: tweet-topics-db
server.port: 8082

tweet:
  app-name: topics-tracker
  o-auth-consumer-key: ri3yzX4VtYhZyHv9LYyGMr6C3
  o-auth-consumer-secret: usbBrSM3F2yoi8JRDTYz3TuJdccqkr3p2ZMFCAHZzg3PV2rSHi
  access-token: 108006069-BkPIkey1hwm5VWKQPc0Op53EibjBeqrCH79CRwhy
  access-token-secret: ximmt4RiBoDawuj3unzbcI1gop9sSygawEllnGL3Z71fU
  bearer-token: AAAAAAAAAAAAAAAAAAAAAHflcQEAAAAAyWQf%2BNq4uzCbQuoVPpKh7LCTv7s%3DEqSADviPyrPmAV11fg6lawxXJCeNEnSbhs010V1zO89nYnGn6T

#logging:
#  level:
#    org.springframework.web.client.RestTemplate: DEBUG